quarkus:
  log:
    level: INFO
  http:
    port: 8790
    cors:
      ~: true
      origins: http://localhost:5173,  https://52f9-125-166-121-121.ngrok-free.app
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, DELETE, PUT, PATCH
  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3306/penilaian_karyawan
  hibernate-orm:
    database:
      generation:
        ~: none
